# Generated by Django 2.1.1 on 2020-02-25 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.DateField(blank=True, null=True)),
                ('property', models.CharField(blank=True, max_length=50, null=True)),
                ('post_code', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.CharField(blank=True, max_length=255, null=True)),
                ('price_one', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_two', models.DecimalField(decimal_places=2, max_digits=6)),
                ('upfront', models.CharField(blank=True, max_length=255, null=True)),
                ('bills', models.DecimalField(decimal_places=2, max_digits=6)),
                ('min_length', models.CharField(blank=True, max_length=255, null=True)),
                ('licensor', models.CharField(blank=True, max_length=255, null=True)),
                ('n_b', models.IntegerField(default=0)),
                ('deposit_rent', models.CharField(blank=True, max_length=255, null=True)),
                ('extra', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.CharField(blank=True, max_length=255, null=True)),
                ('photos_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flats.Flat')),
            ],
        ),
    ]
