# Generated by Django 2.1.1 on 2020-02-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='date_to_rent',
            new_name='available_from',
        ),
    ]
