# Generated by Django 2.1.1 on 2020-02-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_auto_20200222_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='photos_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
