# Generated by Django 2.1.1 on 2020-03-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_auto_20200301_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='available_from',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
