# Generated by Django 2.1.1 on 2020-02-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0003_auto_20200222_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='number_bedrooms',
            new_name='n_b',
        ),
    ]
