# Generated by Django 2.1.1 on 2020-02-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0004_auto_20200225_2206'),
        ('flats', '0004_auto_20200225_2212'),
    ]

    operations = [
    ]
