# Generated by Django 2.1.1 on 2020-02-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0004_auto_20200225_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='length',
            new_name='min_length',
        ),
    ]
