# Generated by Django 2.1.1 on 2020-02-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0004_auto_20200225_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='number_bedrooms',
            field=models.IntegerField(default=0),
        ),
    ]
